#!/usr/bin/env python3
"""
Generate docs/index/*.md index files.

Each generated file lists .md files under docs/ with links relative from
docs/index/*.  The index files themselves are excluded to prevent
self-referential links.
"""
import os
import re
import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve() if "__file__" in dir() else Path(__file__).parent
DOCS_DIR = SCRIPT_DIR.parent
INDEX_DIR = DOCS_DIR / "index"
GENERATED_DIR = DOCS_DIR / ".generated"

INDEX_DIR.mkdir(parents=True, exist_ok=True)
GENERATED_DIR.mkdir(parents=True, exist_ok=True)

# Index files — excluded from listings to prevent self-referential links
INDEX_FILES = {
    INDEX_DIR / "planning.md",
    INDEX_DIR / "specs.md",
    INDEX_DIR / "research.md",
    INDEX_DIR / "worklogs.md",
    INDEX_DIR / "other.md",
    INDEX_DIR / "raw-all.md",
    INDEX_DIR / "index.md",
}

EXCLUDE_DIRS = {".generated", ".vitepress", "node_modules"}

def scan_md_files():
    """Walk DOCS_DIR and return sorted list of non-symlink .md Path objects."""
    md_files = []
    for root, dirs, files in os.walk(DOCS_DIR):
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        for fname in files:
            if fname.endswith(".md"):
                fpath = Path(root) / fname
                if not fpath.is_symlink() and fpath not in INDEX_FILES:
                    md_files.append(fpath)
    md_files.sort()
    return md_files

def rel_from_docs(fpath):
    return str(fpath.relative_to(DOCS_DIR))

def link_from_index(rel):
    # From docs/index/*.md go up one dir to docs/ then into rel
    return f"../{rel}"

def write_bucket(title, out_path, pattern):
    regex = re.compile(pattern, re.IGNORECASE)
    lines = [f"# {title}\n\n", "Autogenerated by docs/scripts/generate-doc-index.sh\n\n"]
    count = 0
    for fpath in md_files:
        rel = rel_from_docs(fpath)
        if regex.search(str(rel)):
            lines.append(f"- [{rel}]({link_from_index(rel)})\n")
            count += 1
    with open(out_path, "w") as f:
        f.writelines(lines)
    return count

md_files = scan_md_files()
print(f"Scanning docs/ — {len(md_files)} files (excluding index files)")

# Raw/All
raw_lines = ["# Raw/All\n\n", "Autogenerated by docs/scripts/generate-doc-index.sh\n\n"]
for fpath in md_files:
    rel = rel_from_docs(fpath)
    raw_lines.append(f"- [{rel}]({link_from_index(rel)})\n")
with open(INDEX_DIR / "raw-all.md", "w") as f:
    f.writelines(raw_lines)
print(f"  raw-all.md: {len(md_files)} entries")

# Buckets
for label, fname, pat in [
    ("Planning", "planning.md", r"(plan|roadmap|wbs|backlog|planning)"),
    ("Specs",    "specs.md",    r"(spec|prd|adr|requirements)"),
    ("Research", "research.md", r"(research|analysis|spike)"),
    ("Worklogs", "worklogs.md",r"(worklog|session|report|reports)"),
    ("Other",    "other.md",    r"."),
]:
    n = write_bucket(label, INDEX_DIR / fname, pat)
    print(f"  {fname}: {n} entries")

with open(GENERATED_DIR / "doc-index.json", "w") as f:
    json.dump({"generated": True, "tool": "docs/scripts/generate-doc-index.sh"}, f, indent=2)
print("Done.")
