#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
DOCS_DIR="$ROOT_DIR/docs"
mkdir -p "$DOCS_DIR/index" "$DOCS_DIR/.generated"

if command -v rg >/dev/null 2>&1; then
  all_files=$(rg --files "$DOCS_DIR" \
    -g "**/*.md" \
    -g "!**/.generated/**" \
    -g "!**/coverage/**" \
    -g "!**/dist/**" \
    -g "!**/.archive/**" \
    -g "!**/default/**" \
    | sort)
else
  all_files=$(find "$DOCS_DIR" -type f -name "*.md" \
    ! -path "*/node_modules/*" \
    ! -path "*/.worktrees/*" \
    ! -path "*/.generated/*" \
    ! -path "*/coverage/*" \
    ! -path "*/dist/*" \
    ! -path "*/.archive/*" \
    ! -path "*/default/*" \
    | sort)
fi

to_relative_link() {
  local rel="$1"
  local route="${rel%*.md}"
  if [[ "$route" == "index" ]]; then
    printf '/'
  elif [[ "$route" == */index ]]; then
    printf '/%s/' "${route%/index}"
  else
    printf '/%s' "$route"
  fi
}

write_bucket() {
  local title="$1"
  local out="$2"
  local pattern="$3"

  {
    echo "# $title"
    echo
    echo "Autogenerated by docs/scripts/generate-doc-index.sh"
    echo
    while IFS= read -r f; do
      rel="${f#${DOCS_DIR}/}"
      rel_lc="$(printf '%s' "$rel" | tr '[:upper:]' '[:lower:]')"
      if [[ "$rel_lc" =~ $pattern ]]; then
        link_target="$(to_relative_link "$rel")"
        echo "- [$rel](${link_target})"
      fi
    done <<< "$all_files"
  } > "$out"
}

{
  echo "# Raw/All"
  echo
  echo "Autogenerated by docs/scripts/generate-doc-index.sh"
  echo
  while IFS= read -r f; do
    rel="${f#${DOCS_DIR}/}"
    echo "- [$rel]($(to_relative_link "$rel"))"
  done <<< "$all_files"
} > "$DOCS_DIR/index/raw-all.md"

write_bucket "Planning" "$DOCS_DIR/index/planning.md" '(^|/)(plan|planning|wbs|backlog|roadmap)([^a-z]|$)'
write_bucket "Specs" "$DOCS_DIR/index/specs.md" '(^|/)(spec|requirements|adr|prd)([^a-z]|$)'
write_bucket "Research" "$DOCS_DIR/index/research.md" '(^|/)(research|analysis|spike)'
write_bucket "Worklogs" "$DOCS_DIR/index/worklogs.md" '(^|/)(worklog|session|report|reports)'
write_bucket "Other" "$DOCS_DIR/index/other.md" '.*'

printf '{\n  "generated": true,\n  "tool": "docs/scripts/generate-doc-index.sh"\n}\n' > "$DOCS_DIR/.generated/doc-index.json"
